// Generated by workflow 706 (convert-clone-to-routes.mjs) from
// FFC-Cloudflare-Automation/assets/ffc-footer.tsx, then adapted for this site:
// a pre-501c3 (Level 1) footer that renders identity, policy links and the
// permanent "Supported by" attribution, and nothing it cannot truthfully claim.
import Link from 'next/link'
import { siteConfig } from '@/lib/site.config'

/**
 * Standard attribution footer, rendered site-wide below the cloned page chrome
 * (the cloned pages keep their own visual footer; this strip carries the
 * supporting-program attribution and the legal/policy links).
 *
 * Footer-standard checklist items covered here:
 *   1. Site identity — name, plus EIN linked to the Candid profile at Level 2.
 *   2. Permanent "Supported by" attribution to the supporting organization.
 *   3. "Supported Charity Login" link to the supporting organization's hub.
 *   4. Copyright line with the build year and the site's name.
 *   5. Policy links.
 *
 * Level 1 vs Level 2. The EIN line, the Candid link and the tax-status clause
 * are Level 2 items for an organization with IRS recognition. The shared
 * SiteConfig schema requires `ein` and the Candid URLs to be non-empty, so a
 * pre-501c3 site carries sentinels; the gate below is the SHAPE of the EIN,
 * never its mere presence, so a sentinel can never render as a legal claim.
 */

/** A real IRS Employer Identification Number: two digits, hyphen, seven digits. */
const EIN_SHAPE = /^\d{2}-\d{7}$/

/**
 * The parent organization to ASSERT, or null.
 *
 * `supportedBy` and `parentOrg` are different claims. The first is the program
 * attribution required on every supported site. The second is genuine fiscal
 * sponsorship ("a project of"), which says the site's organization is NOT
 * independent. A `parentOrg` that merely repeats `supportedBy` is the template
 * default wearing a different label and is not asserted. Compared on name OR
 * url so that retitling or repointing only one half still reads as the same
 * organization.
 */
function assertedParentOrg() {
  const parent = siteConfig.parentOrg
  if (!parent) return null
  const norm = (s: string) => s.trim().toLowerCase().replace(/\/+$/, '')
  const same =
    norm(parent.name) === norm(siteConfig.supportedBy.name) ||
    norm(parent.url) === norm(siteConfig.supportedBy.url)
  return same ? null : parent
}

export default function FfcFooter() {
  const year = new Date().getFullYear()
  const parentOrg = assertedParentOrg()
  const rawEin = siteConfig.ein?.trim() ?? ''
  const ein = EIN_SHAPE.test(rawEin) ? rawEin : ''
  const candidUrl = ein ? (siteConfig.guidestar?.profileUrl?.trim() ?? '') : ''
  // The tax-status clause is "both-or-neither" with the EIN line and the
  // Candid link: it can never appear without them. The WORDING comes from the
  // config so the two footers never state the same claim two different ways.
  const taxStatusLabel = ein && candidUrl ? siteConfig.taxStatusLabel.trim() : ''
  // The footer standard's minimum policy set: privacy, cookies, terms, both
  // donation policies, vulnerability disclosure, security acknowledgements.
  const policyLinks = [
    { name: 'Privacy Policy', href: '/privacy-policy' },
    { name: 'Cookie Policy', href: '/cookie-policy' },
    { name: 'Terms of Service', href: '/terms-of-service' },
    { name: 'Donation Policy', href: '/donation-policy' },
    { name: 'FFC Donation Policy', href: '/free-for-charity-donation-policy' },
    { name: 'Vulnerability Disclosure', href: '/vulnerability-disclosure-policy' },
    { name: 'Security Acknowledgements', href: '/security-acknowledgements' },
  ]
  const identity = ein ? `${siteConfig.name} — EIN ${ein}` : siteConfig.name

  return (
    <footer className="ffc-footer" aria-label="Site information and policies">
      <div className="ffc-footer__inner">
        <p className="ffc-footer__identity">
          {ein && candidUrl ? (
            <a
              href={candidUrl}
              target="_blank"
              rel="noopener noreferrer"
              // The accessible name must contain the visible text
              // (axe "label-content-name-mismatch"), so lead with it.
              aria-label={`${identity} — view the nonprofit profile on Candid`}
            >
              {identity}
            </a>
          ) : (
            identity
          )}
        </p>

        <ul className="ffc-footer__links">
          {policyLinks.map((link) => (
            <li key={link.href}>
              <Link href={link.href}>{link.name}</Link>
            </li>
          ))}
          <li>
            <a href={siteConfig.supportedBy.hubUrl} target="_blank" rel="noopener noreferrer">
              Supported Charity Login
            </a>
          </li>
          <li>
            <a href={`mailto:${siteConfig.contactEmail}`}>{siteConfig.contactEmail}</a>
          </li>
        </ul>

        {/* The footer standard's bottom bar, word for word as the template
            renders it. tests/copyright.spec.ts asserts on this phrasing, and
            the "Supported by" clause is a permanent program attribution that
            must never be removed or hidden when a site is customized. */}
        <p className="ffc-footer__legal">
          © {year} All Rights Are Reserved by {siteConfig.name}
          {taxStatusLabel ? ` ${taxStatusLabel}` : ''}
          {' | Supported by '}
          <a href={siteConfig.supportedBy.url} target="_blank" rel="noopener noreferrer">
            {siteConfig.supportedBy.name}
          </a>
          {parentOrg && (
            <>
              {' | A project of '}
              <a href={parentOrg.url} target="_blank" rel="noopener noreferrer">
                {parentOrg.name}
              </a>
            </>
          )}
        </p>

        {/* Said in words, because "Supported by" alone has been read as
            ownership. The line renders only when there is NO asserted parent;
            a site that genuinely is a project of an umbrella org must not
            claim to be independent. */}
        {!parentOrg && (
          <p className="ffc-footer__relationship">
            <a href={siteConfig.supportedBy.url} target="_blank" rel="noopener noreferrer">
              {siteConfig.supportedBy.name}
            </a>{' '}
            provides this website and its domain services at no cost. {siteConfig.name} is an
            independent organization, responsible for its own content and operations.
          </p>
        )}
      </div>
    </footer>
  )
}
