import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Contact | Make A Calendar Invite' },
  description: 'Ensure your appointments and events are never missed. Create a calendar invite today and keep everyone in the loop. (123) 456-7890 info@makeacalendarinvite. ...',
  openGraph: {
    title: 'Contact | Make A Calendar Invite',
    description: 'Ensure your appointments and events are never missed. Create a calendar invite today and keep everyone in the loop. (123) 456-7890 info@makeacalendarinvite. ...',
    url: '/contact/',
    type: 'article',
  },
  twitter: {
    title: 'Contact | Make A Calendar Invite',
    description: 'Ensure your appointments and events are never missed. Create a calendar invite today and keep everyone in the loop. (123) 456-7890 info@makeacalendarinvite. ...',
  },
  alternates: { canonical: '/contact/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-15 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('contact') }}
    />
  )
}
