import { pageMetadata } from '@/lib/pageMetadata'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by the live-site capture (.github/workflows/capture-live-site.yml,
// using FFC-Cloudflare-Automation's convert-clone-to-routes). Edit the source
// site and re-capture rather than this file; the markup lives in
// src/clone-content/contact.html.
export const metadata = pageMetadata({
  title: 'Contact',
  description:
    'Ensure your appointments and events are never missed. Create a calendar invite today and keep everyone in the loop. (123) 456-7890 info@makeacalendarinvite. ...',
  path: '/contact/',
})

export default function Page() {
  return (
    <main id="main-content">
      <div
        className="ffc-clone wp-singular page-template-default page page-id-15 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
        dangerouslySetInnerHTML={{ __html: loadCloneContent('contact') }}
      />
    </main>
  )
}
