import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Sample Page | Make A Calendar Invite' },
  description: 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). M ...',
  openGraph: {
    title: 'Sample Page | Make A Calendar Invite',
    description: 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). M ...',
    url: '/sample-page/',
    type: 'article',
  },
  twitter: {
    title: 'Sample Page | Make A Calendar Invite',
    description: 'This is an example page. It\'s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). M ...',
  },
  alternates: { canonical: '/sample-page/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-2 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_right_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('sample-page') }}
    />
  )
}
