import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Hello world! | Make A Calendar Invite' },
  description: 'Welcome to WordPress. This is your first post. Edit or delete it, then start writing!',
  openGraph: {
    title: 'Hello world! | Make A Calendar Invite',
    description: 'Welcome to WordPress. This is your first post. Edit or delete it, then start writing!',
    url: '/hello-world/',
    type: 'article',
  },
  twitter: {
    title: 'Hello world! | Make A Calendar Invite',
    description: 'Welcome to WordPress. This is your first post. Edit or delete it, then start writing!',
  },
  alternates: { canonical: '/hello-world/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular post-template-default single single-post postid-1 single-format-standard wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-body et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('hello-world') }}
    />
  )
}
