import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Home | Make A Calendar Invite' },
  description: 'Ensure your appointments and events are never missed by sending a calendar invite. Simplify scheduling and boost attendance with our easy-to-use tool. Sendi ...',
  openGraph: {
    title: 'Home | Make A Calendar Invite',
    description: 'Ensure your appointments and events are never missed by sending a calendar invite. Simplify scheduling and boost attendance with our easy-to-use tool. Sendi ...',
    url: '/',
    type: 'article',
  },
  twitter: {
    title: 'Home | Make A Calendar Invite',
    description: 'Ensure your appointments and events are never missed by sending a calendar invite. Simplify scheduling and boost attendance with our easy-to-use tool. Sendi ...',
  },
  alternates: { canonical: '/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-7 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
