import { pageMetadata } from '@/lib/pageMetadata'
import { loadCloneContent } from '@/lib/clone-content'
import { siteConfig } from '@/lib/site.config'

// Generated by the live-site capture (.github/workflows/capture-live-site.yml,
// using FFC-Cloudflare-Automation's convert-clone-to-routes). Edit the source
// site and re-capture rather than this file; the markup lives in
// src/clone-content/index.html.
// The root route shares its segment with the layout, so the layout's
// `title.template` does NOT apply here: a bare 'Home' would ship as the whole
// <title>. Spell the landing page's title out in full instead.
export const metadata = {
  ...pageMetadata({
    title: 'Home',
    description:
      'Ensure your appointments and events are never missed by sending a calendar invite. Simplify scheduling and boost attendance with our easy-to-use tool. Sendi ...',
    path: '/',
  }),
  title: { absolute: `${siteConfig.name} | ${siteConfig.tagline}` },
}

export default function Page() {
  return (
    <main id="main-content">
      <div
        className="ffc-clone home wp-singular page-template-default page page-id-7 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
        dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
      />
    </main>
  )
}
