import { pageMetadata } from '@/lib/pageMetadata'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by the live-site capture (.github/workflows/capture-live-site.yml,
// using FFC-Cloudflare-Automation's convert-clone-to-routes). Edit the source
// site and re-capture rather than this file; the markup lives in
// src/clone-content/why.html.
export const metadata = pageMetadata({
  title: 'Why',
  description:
    'Sending calendar invites is a fundamental practice for effective communication and organization. They help ensure that everyone is on the same page, reducin ...',
  path: '/why/',
})

export default function Page() {
  return (
    <main id="main-content">
      <div
        className="ffc-clone wp-singular page-template-default page page-id-9 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
        dangerouslySetInnerHTML={{ __html: loadCloneContent('why') }}
      />
    </main>
  )
}
