import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Why | Make A Calendar Invite' },
  description: 'Sending calendar invites is a fundamental practice for effective communication and organization. They help ensure that everyone is on the same page, reducin ...',
  openGraph: {
    title: 'Why | Make A Calendar Invite',
    description: 'Sending calendar invites is a fundamental practice for effective communication and organization. They help ensure that everyone is on the same page, reducin ...',
    url: '/why/',
    type: 'article',
  },
  twitter: {
    title: 'Why | Make A Calendar Invite',
    description: 'Sending calendar invites is a fundamental practice for effective communication and organization. They help ensure that everyone is on the same page, reducin ...',
  },
  alternates: { canonical: '/why/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-9 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('why') }}
    />
  )
}
