import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Tips | Make A Calendar Invite' },
  description: 'Discover the secrets to making your calendar invites irresistible and ensure your events are never missed. Don\'t let your events go unnoticed. Follow o ...',
  openGraph: {
    title: 'Tips | Make A Calendar Invite',
    description: 'Discover the secrets to making your calendar invites irresistible and ensure your events are never missed. Don\'t let your events go unnoticed. Follow o ...',
    url: '/tips/',
    type: 'article',
  },
  twitter: {
    title: 'Tips | Make A Calendar Invite',
    description: 'Discover the secrets to making your calendar invites irresistible and ensure your events are never missed. Don\'t let your events go unnoticed. Follow o ...',
  },
  alternates: { canonical: '/tips/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-13 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('tips') }}
    />
  )
}
