import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'How | Make A Calendar Invite' },
  description: 'Discover the essential steps to creating effective calendar invites that ensure your events are well-attended. Open your calendar application and navigate t ...',
  openGraph: {
    title: 'How | Make A Calendar Invite',
    description: 'Discover the essential steps to creating effective calendar invites that ensure your events are well-attended. Open your calendar application and navigate t ...',
    url: '/how/',
    type: 'article',
  },
  twitter: {
    title: 'How | Make A Calendar Invite',
    description: 'Discover the essential steps to creating effective calendar invites that ensure your events are well-attended. Open your calendar application and navigate t ...',
  },
  alternates: { canonical: '/how/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-11 wp-theme-Divi et-tb-has-template et-tb-has-header et-tb-has-footer et_pb_button_helper_class et_cover_background et_pb_gutter et_pb_gutters3 et_pb_pagebuilder_layout et_no_sidebar et_divi_theme et-db"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('how') }}
    />
  )
}
