import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Free For Charity' },
  openGraph: {
    title: 'Free For Charity',
    url: '/hub/',
    type: 'article',
  },
  twitter: {
    title: 'Free For Charity',
  },
  alternates: { canonical: '/hub/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('hub') }}
    />
  )
}
